/* Additional record code for ThermalPlant generated by the OpenModelica Compiler OpenModelica 1.27.1~1-g562f07f. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ThermalPlant_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

