#include "simulation_data.h"
#include "util/real_array.h"

OMC_DISABLE_OPT

void ThermalPlant_read_simulation_info(SIMULATION_INFO* simulationInfo)
{
  simulationInfo->startTime = 0.0;
  simulationInfo->stopTime = 1.0;
  simulationInfo->stepSize = 0.002;
  simulationInfo->tolerance = 1e-6;
  simulationInfo->solverMethod = "dassl";
  simulationInfo->outputFormat = "mat";
  simulationInfo->variableFilter = ".*";
  simulationInfo->OPENMODELICAHOME = "/usr/bin/..";
}

void ThermalPlant_read_input_fmu(MODEL_DATA* modelData)
{
  modelData->realVarsData[0].info.id = 1000;
  modelData->realVarsData[0].info.name = "$outputAlias_temperature";
  modelData->realVarsData[0].info.comment = "Simulated temperature [degC]";
  modelData->realVarsData[0].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realVarsData[0].info.info.lineStart = 19;
  modelData->realVarsData[0].info.info.colStart = 3;
  modelData->realVarsData[0].info.info.lineEnd = 20;
  modelData->realVarsData[0].info.info.colEnd = 35;
  modelData->realVarsData[0].info.info.readonly = 0;
  modelData->realVarsData[0].attribute.unit = "";
  modelData->realVarsData[0].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[0].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[0].attribute.max);
  modelData->realVarsData[0].attribute.fixed = 0;
  modelData->realVarsData[0].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[0].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[0].attribute.start);
  modelData->realVarsData[1].info.id = 1001;
  modelData->realVarsData[1].info.name = "der($outputAlias_temperature)";
  modelData->realVarsData[1].info.comment = "der(Simulated temperature [degC])";
  modelData->realVarsData[1].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realVarsData[1].info.info.lineStart = 19;
  modelData->realVarsData[1].info.info.colStart = 3;
  modelData->realVarsData[1].info.info.lineEnd = 20;
  modelData->realVarsData[1].info.info.colEnd = 35;
  modelData->realVarsData[1].info.info.readonly = 0;
  modelData->realVarsData[1].attribute.unit = "";
  modelData->realVarsData[1].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[1].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[1].attribute.max);
  modelData->realVarsData[1].attribute.fixed = 0;
  modelData->realVarsData[1].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[1].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[1].attribute.start);
  modelData->realVarsData[2].info.id = 1002;
  modelData->realVarsData[2].info.name = "$temperature_der";
  modelData->realVarsData[2].info.comment = "";
  modelData->realVarsData[2].info.info.filename = "";
  modelData->realVarsData[2].info.info.lineStart = 0;
  modelData->realVarsData[2].info.info.colStart = 0;
  modelData->realVarsData[2].info.info.lineEnd = 0;
  modelData->realVarsData[2].info.info.colEnd = 0;
  modelData->realVarsData[2].info.info.readonly = 0;
  modelData->realVarsData[2].attribute.unit = "";
  modelData->realVarsData[2].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[2].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[2].attribute.max);
  modelData->realVarsData[2].attribute.fixed = 0;
  modelData->realVarsData[2].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[2].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[2].attribute.start);
  modelData->realVarsData[3].info.id = 1003;
  modelData->realVarsData[3].info.name = "ambient";
  modelData->realVarsData[3].info.comment = "Ambient temperature [degC]";
  modelData->realVarsData[3].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realVarsData[3].info.info.lineStart = 16;
  modelData->realVarsData[3].info.info.colStart = 3;
  modelData->realVarsData[3].info.info.lineEnd = 17;
  modelData->realVarsData[3].info.info.colEnd = 33;
  modelData->realVarsData[3].info.info.readonly = 0;
  modelData->realVarsData[3].attribute.unit = "";
  modelData->realVarsData[3].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[3].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[3].attribute.max);
  modelData->realVarsData[3].attribute.fixed = 1;
  modelData->realVarsData[3].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[3].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[3].attribute.start);
  modelData->realVarsData[4].info.id = 1004;
  modelData->realVarsData[4].info.name = "power";
  modelData->realVarsData[4].info.comment = "Applied power [W]";
  modelData->realVarsData[4].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realVarsData[4].info.info.lineStart = 13;
  modelData->realVarsData[4].info.info.colStart = 3;
  modelData->realVarsData[4].info.info.lineEnd = 14;
  modelData->realVarsData[4].info.info.colEnd = 24;
  modelData->realVarsData[4].info.info.readonly = 0;
  modelData->realVarsData[4].attribute.unit = "";
  modelData->realVarsData[4].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[4].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[4].attribute.max);
  modelData->realVarsData[4].attribute.fixed = 1;
  modelData->realVarsData[4].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[4].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[4].attribute.start);
  modelData->realVarsData[5].info.id = 1005;
  modelData->realVarsData[5].info.name = "temperature";
  modelData->realVarsData[5].info.comment = "Simulated temperature [degC]";
  modelData->realVarsData[5].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realVarsData[5].info.info.lineStart = 19;
  modelData->realVarsData[5].info.info.colStart = 3;
  modelData->realVarsData[5].info.info.lineEnd = 20;
  modelData->realVarsData[5].info.info.colEnd = 35;
  modelData->realVarsData[5].info.info.readonly = 0;
  modelData->realVarsData[5].attribute.unit = "";
  modelData->realVarsData[5].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realVarsData[5].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realVarsData[5].attribute.max);
  modelData->realVarsData[5].attribute.fixed = 0;
  modelData->realVarsData[5].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realVarsData[5].attribute.nominal);
  put_real_element(0.0, 0, &modelData->realVarsData[5].attribute.start);
  modelData->realParameterData[0].info.id = 1006;
  modelData->realParameterData[0].info.name = "C";
  modelData->realParameterData[0].info.comment = "Thermal capacitance [J/K]";
  modelData->realParameterData[0].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realParameterData[0].info.info.lineStart = 7;
  modelData->realParameterData[0].info.info.colStart = 3;
  modelData->realParameterData[0].info.info.lineEnd = 8;
  modelData->realParameterData[0].info.info.colEnd = 32;
  modelData->realParameterData[0].info.info.readonly = 0;
  modelData->realParameterData[0].attribute.unit = "";
  modelData->realParameterData[0].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[0].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[0].attribute.max);
  modelData->realParameterData[0].attribute.fixed = 1;
  modelData->realParameterData[0].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[0].attribute.nominal);
  put_real_element(100.0, 0, &modelData->realParameterData[0].attribute.start);
  modelData->realParameterData[1].info.id = 1007;
  modelData->realParameterData[1].info.name = "R";
  modelData->realParameterData[1].info.comment = "Thermal resistance [K/W]";
  modelData->realParameterData[1].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realParameterData[1].info.info.lineStart = 4;
  modelData->realParameterData[1].info.info.colStart = 3;
  modelData->realParameterData[1].info.info.lineEnd = 5;
  modelData->realParameterData[1].info.info.colEnd = 31;
  modelData->realParameterData[1].info.info.readonly = 0;
  modelData->realParameterData[1].attribute.unit = "";
  modelData->realParameterData[1].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[1].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[1].attribute.max);
  modelData->realParameterData[1].attribute.fixed = 1;
  modelData->realParameterData[1].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[1].attribute.nominal);
  put_real_element(0.5, 0, &modelData->realParameterData[1].attribute.start);
  modelData->realParameterData[2].info.id = 1008;
  modelData->realParameterData[2].info.name = "T_start";
  modelData->realParameterData[2].info.comment = "Initial temperature [degC]";
  modelData->realParameterData[2].info.info.filename = "/home/arnab/Projects/openmodelica-pytorch-hybrid/modelica/ThermalPlant.mo";
  modelData->realParameterData[2].info.info.lineStart = 10;
  modelData->realParameterData[2].info.info.colStart = 3;
  modelData->realParameterData[2].info.info.lineEnd = 11;
  modelData->realParameterData[2].info.info.colEnd = 33;
  modelData->realParameterData[2].info.info.readonly = 0;
  modelData->realParameterData[2].attribute.unit = "";
  modelData->realParameterData[2].attribute.displayUnit = "";
  put_real_element(-DBL_MAX, 0, &modelData->realParameterData[2].attribute.min);
  put_real_element(DBL_MAX, 0, &modelData->realParameterData[2].attribute.max);
  modelData->realParameterData[2].attribute.fixed = 1;
  modelData->realParameterData[2].attribute.useNominal = 0;
  put_real_element(1.0, 0, &modelData->realParameterData[2].attribute.nominal);
  put_real_element(25.0, 0, &modelData->realParameterData[2].attribute.start);
}